FROM node:16 as base

WORKDIR /app

ENV PORT=8080

ENV DATABASE_URL=mongodb+srv://<name>:<password>@planeja-db.pf8a9zu.mongodb.net/?retryWrites=true&w=majority
COPY package*.json ./

RUN npm i

COPY . . 

RUN npm run build

RUN chown -R $user:$user /app

USER $user

CMD npm start

EXPOSE 8080